### ISSUE TITLE
Theme - Black

### ISSUE THREAD

**Issue by stelian87** [atanasster/grommet-nextjs#13]
Hello,

i'm getting this error on page refresh after i updated to grommet packages:
{ /home/dragos/japp-japp/node_modules/grommet/es6/utils/object.js:3
export var isObject = function isObject(item) {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dragos/japp-japp/node_modules/grommet-controls/themes/black.js:5:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17) sourceMapsApplied: true }
/home/dragos/japp-japp/node_modules/grommet/es6/utils/object.js:3

--------------------------------------------------
My package.json is:
...
    "grommet": "^2.4.0",
    "grommet-controls": "^1.1.6",
    "grommet-icons": "^4.2.0",
...

Any ideas? i'm in the dark here

EDIT: the trouble seems to start with package 1.1.2. 
the 1.1.1. package is ok

**Comment by stelian87** [comment]
the line that was the issue is:
var _object = require("grommet/utils/object"); 
vs
var _object = require("grommet/es6/utils/object");

Can you please tell me what's the difference? 
do you have a link with instructions on how to convert to es6? is it necessary to do so?

**Comment by atanasster** [comment]
Hi @stelian87 - sorry about this, I am trying to find a way to remove some of the extra code linked from `grommet`, but I guess your system is not set up for es6 modules.

Anyway, I reverted most of the changes - can you please update to 1.1.8
